### PR TITLE
added Gemfile

### PR DESCRIPTION
**Pull request by choose-goose**

### CODE REVIEW

**Comment by makers-dev** [comment]
You need to put your pair partners

**Comment by makers-dev** [comment]
You need to add issues

**Comment by choose-goose** [comment]
pair:@lemonsweets
closes #1

**Comment by makers-dev** [comment]
Thanks for your submission, a coach will review it shortly

**Comment by rubenkostucki** [comment]
Mate, you're missing stuff

**Comment by rubenkostucki** [comment]
:construction:

**Pull request merged**
